env:
  browser: true
  es2024: true
  jest: true
extends: 
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaVersion: latest
  ecmaFeatures:
    impliedStrict: true
    jsx: true
  sourceType: module
plugins:
  - react
settings:
  react:
    version: detect
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars: 
    - off
  react/prop-types:
    - off
  no-console:
    - off
globals:
  pug: false

